<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $countries = [
            ['code' => 'AF', 'name' => 'Afghanistan'],
            ['code' => 'AL', 'name' => 'Albania'],
            ['code' => 'DE', 'name' => 'Germany'],
            ['code' => 'AD', 'name' => 'Andorra'],
            ['code' => 'AO', 'name' => 'Angola'],
            ['code' => 'AI', 'name' => 'Anguilla'],
            ['code' => 'AQ', 'name' => 'Antarctica'],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda'],
            ['code' => 'SA', 'name' => 'Saudi Arabia'],
            ['code' => 'DZ', 'name' => 'Algeria'],
            ['code' => 'AR', 'name' => 'Argentina'],
            ['code' => 'AM', 'name' => 'Armenia'],
            ['code' => 'AW', 'name' => 'Aruba'],
            ['code' => 'AU', 'name' => 'Australia'],
            ['code' => 'AT', 'name' => 'Austria'],
            ['code' => 'AZ', 'name' => 'Azerbaijan'],
            ['code' => 'BS', 'name' => 'Bahamas'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'area' => [ 'district', 'zillah', 'upozillah', 'union', 'city corporation' ]],
            ['code' => 'BB', 'name' => 'Barbados'],
            ['code' => 'BH', 'name' => 'Bahrain'],
            ['code' => 'BE', 'name' => 'Belgium'],
            ['code' => 'BZ', 'name' => 'Belize'],
            ['code' => 'BJ', 'name' => 'Benin'],
            ['code' => 'BM', 'name' => 'Bermuda'],
            ['code' => 'BY', 'name' => 'Belarus'],
            ['code' => 'BO', 'name' => 'Bolivia'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
            ['code' => 'BW', 'name' => 'Botswana'],
            ['code' => 'BR', 'name' => 'Brazil'],
            ['code' => 'BN', 'name' => 'Brunei'],
            ['code' => 'BG', 'name' => 'Bulgaria'],
            ['code' => 'BF', 'name' => 'Burkina Faso'],
            ['code' => 'BI', 'name' => 'Burundi'],
            ['code' => 'BT', 'name' => 'Bhutan'],
            ['code' => 'CV', 'name' => 'Cape Verde'],
            ['code' => 'KH', 'name' => 'Cambodia'],
            ['code' => 'CM', 'name' => 'Cameroon'],
            ['code' => 'CA', 'name' => 'Canada'],
            ['code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba'],
            ['code' => 'QA', 'name' => 'Qatar'],
            ['code' => 'TD', 'name' => 'Chad'],
            ['code' => 'CZ', 'name' => 'Czech Republic'],
            ['code' => 'CL', 'name' => 'Chile'],
            ['code' => 'CN', 'name' => 'China'],
            ['code' => 'CY', 'name' => 'Cyprus'],
            ['code' => 'VA', 'name' => 'Vatican City'],
            ['code' => 'CO', 'name' => 'Colombia'],
            ['code' => 'KM', 'name' => 'Comoros'],
            ['code' => 'CG', 'name' => 'Congo'],
            ['code' => 'KP', 'name' => 'North Korea'],
            ['code' => 'KR', 'name' => 'South Korea'],
            ['code' => 'CR', 'name' => 'Costa Rica'],
            ['code' => 'CI', 'name' => 'Ivory Coast'],
            ['code' => 'HR', 'name' => 'Croatia'],
            ['code' => 'CU', 'name' => 'Cuba'],
            ['code' => 'CW', 'name' => 'Curaçao'],
            ['code' => 'DK', 'name' => 'Denmark'],
            ['code' => 'DM', 'name' => 'Dominica'],
            ['code' => 'EC', 'name' => 'Ecuador'],
            ['code' => 'EG', 'name' => 'Egypt'],
            ['code' => 'SV', 'name' => 'El Salvador'],
            ['code' => 'AE', 'name' => 'United Arab Emirates'],
            ['code' => 'ER', 'name' => 'Eritrea'],
            ['code' => 'SK', 'name' => 'Slovakia'],
            ['code' => 'SI', 'name' => 'Slovenia'],
            ['code' => 'ES', 'name' => 'Spain'],
            ['code' => 'US', 'name' => 'United States'],
            ['code' => 'EE', 'name' => 'Estonia'],
            ['code' => 'SZ', 'name' => 'Eswatini'],
            ['code' => 'ET', 'name' => 'Ethiopia'],
            ['code' => 'PH', 'name' => 'Philippines'],
            ['code' => 'FI', 'name' => 'Finland'],
            ['code' => 'FJ', 'name' => 'Fiji'],
            ['code' => 'FR', 'name' => 'France'],
            ['code' => 'GA', 'name' => 'Gabon'],
            ['code' => 'GM', 'name' => 'Gambia'],
            ['code' => 'GE', 'name' => 'Georgia'],
            ['code' => 'GH', 'name' => 'Ghana'],
            ['code' => 'GI', 'name' => 'Gibraltar'],
            ['code' => 'GD', 'name' => 'Grenada'],
            ['code' => 'GR', 'name' => 'Greece'],
            ['code' => 'GL', 'name' => 'Greenland'],
            ['code' => 'GP', 'name' => 'Guadeloupe'],
            ['code' => 'GU', 'name' => 'Guam'],
            ['code' => 'GT', 'name' => 'Guatemala'],
            ['code' => 'GF', 'name' => 'French Guiana'],
            ['code' => 'GG', 'name' => 'Guernsey'],
            ['code' => 'GN', 'name' => 'Guinea'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau'],
            ['code' => 'GY', 'name' => 'Guyana'],
            ['code' => 'HT', 'name' => 'Haiti'],
            ['code' => 'HN', 'name' => 'Honduras'],
            ['code' => 'HU', 'name' => 'Hungary'],
            ['code' => 'IN', 'name' => 'India'],
            ['code' => 'ID', 'name' => 'Indonesia'],
            ['code' => 'IQ', 'name' => 'Iraq'],
            ['code' => 'IR', 'name' => 'Iran'],
            ['code' => 'IE', 'name' => 'Ireland'],
            ['code' => 'BV', 'name' => 'Bouvet Island'],
            ['code' => 'IM', 'name' => 'Isle of Man'],
            ['code' => 'CX', 'name' => 'Christmas Island'],
            ['code' => 'NF', 'name' => 'Norfolk Island'],
            ['code' => 'IS', 'name' => 'Iceland'],
            ['code' => 'AX', 'name' => 'Åland Islands'],
            ['code' => 'KY', 'name' => 'Cayman Islands'],
            ['code' => 'CC', 'name' => 'Cocos Islands'],
            ['code' => 'CK', 'name' => 'Cook Islands'],
            ['code' => 'FO', 'name' => 'Faroe Islands'],
            ['code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'],
            ['code' => 'HM', 'name' => 'Heard Island and McDonald Islands'],
            ['code' => 'FK', 'name' => 'Falkland Islands'],
            ['code' => 'MP', 'name' => 'Northern Mariana Islands'],
            ['code' => 'MH', 'name' => 'Marshall Islands'],
            ['code' => 'UM', 'name' => 'United States Minor Outlying Islands'],
            ['code' => 'PN', 'name' => 'Pitcairn Islands'],
            ['code' => 'SB', 'name' => 'Solomon Islands'],
            ['code' => 'TC', 'name' => 'Turks and Caicos Islands'],
            ['code' => 'VG', 'name' => 'British Virgin Islands'],
            ['code' => 'VI', 'name' => 'United States Virgin Islands'],
            ['code' => 'IL', 'name' => 'Israel'],
            ['code' => 'IT', 'name' => 'Italy'],
            ['code' => 'JM', 'name' => 'Jamaica'],
            ['code' => 'JP', 'name' => 'Japan'],
            ['code' => 'JE', 'name' => 'Jersey'],
            ['code' => 'JO', 'name' => 'Jordan'],
            ['code' => 'KZ', 'name' => 'Kazakhstan'],
            ['code' => 'KE', 'name' => 'Kenya'],
            ['code' => 'KI', 'name' => 'Kiribati'],
            ['code' => 'KW', 'name' => 'Kuwait'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan'],
            ['code' => 'LA', 'name' => 'Laos'],
            ['code' => 'LV', 'name' => 'Latvia'],
            ['code' => 'LB', 'name' => 'Lebanon'],
            ['code' => 'LS', 'name' => 'Lesotho'],
            ['code' => 'LR', 'name' => 'Liberia'],
            ['code' => 'LY', 'name' => 'Libya'],
            ['code' => 'LI', 'name' => 'Liechtenstein'],
            ['code' => 'LT', 'name' => 'Lithuania'],
            ['code' => 'LU', 'name' => 'Luxembourg'],
            ['code' => 'MO', 'name' => 'Macao'],
            ['code' => 'MG', 'name' => 'Madagascar'],
            ['code' => 'MW', 'name' => 'Malawi'],
            ['code' => 'MY', 'name' => 'Malaysia'],
            ['code' => 'MV', 'name' => 'Maldives'],
            ['code' => 'ML', 'name' => 'Mali'],
            ['code' => 'MT', 'name' => 'Malta'],
            ['code' => 'MQ', 'name' => 'Martinique'],
            ['code' => 'MR', 'name' => 'Mauritania'],
            ['code' => 'MU', 'name' => 'Mauritius'],
            ['code' => 'YT', 'name' => 'Mayotte'],
            ['code' => 'MX', 'name' => 'Mexico'],
            ['code' => 'FM', 'name' => 'Micronesia'],
            ['code' => 'MD', 'name' => 'Moldova'],
            ['code' => 'MC', 'name' => 'Monaco'],
            ['code' => 'MN', 'name' => 'Mongolia'],
            ['code' => 'ME', 'name' => 'Montenegro'],
            ['code' => 'MS', 'name' => 'Montserrat'],
            ['code' => 'MA', 'name' => 'Morocco'],
            ['code' => 'MZ', 'name' => 'Mozambique'],
            ['code' => 'MM', 'name' => 'Myanmar'],
            ['code' => 'NA', 'name' => 'Namibia'],
            ['code' => 'NR', 'name' => 'Nauru'],
            ['code' => 'NP', 'name' => 'Nepal'],
            ['code' => 'NL', 'name' => 'Netherlands'],
            ['code' => 'NZ', 'name' => 'New Zealand'],
            ['code' => 'NI', 'name' => 'Nicaragua'],
            ['code' => 'NE', 'name' => 'Niger'],
            ['code' => 'NG', 'name' => 'Nigeria'],
            ['code' => 'NU', 'name' => 'Niue'],
            ['code' => 'NO', 'name' => 'Norway'],
            ['code' => 'OM', 'name' => 'Oman'],
            ['code' => 'PK', 'name' => 'Pakistan'],
            ['code' => 'PW', 'name' => 'Palau'],
            ['code' => 'PS', 'name' => 'Palestine'],
            ['code' => 'PA', 'name' => 'Panama'],
            ['code' => 'PG', 'name' => 'Papua New Guinea'],
            ['code' => 'PY', 'name' => 'Paraguay'],
            ['code' => 'PE', 'name' => 'Peru'],
            ['code' => 'PL', 'name' => 'Poland'],
            ['code' => 'PT', 'name' => 'Portugal'],
            ['code' => 'PR', 'name' => 'Puerto Rico'],
            ['code' => 'RE', 'name' => 'Réunion'],
            ['code' => 'RO', 'name' => 'Romania'],
            ['code' => 'RU', 'name' => 'Russia'],
            ['code' => 'RW', 'name' => 'Rwanda'],
            ['code' => 'WS', 'name' => 'Samoa'],
            ['code' => 'SM', 'name' => 'San Marino'],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe'],
            ['code' => 'SN', 'name' => 'Senegal'],
            ['code' => 'RS', 'name' => 'Serbia'],
            ['code' => 'SC', 'name' => 'Seychelles'],
            ['code' => 'SL', 'name' => 'Sierra Leone'],
            ['code' => 'SG', 'name' => 'Singapore'],
            ['code' => 'SX', 'name' => 'Sint Maarten'],
            ['code' => 'SE', 'name' => 'Sweden'],
            ['code' => 'CH', 'name' => 'Switzerland'],
            ['code' => 'SY', 'name' => 'Syria'],
            ['code' => 'TJ', 'name' => 'Tajikistan'],
            ['code' => 'TZ', 'name' => 'Tanzania'],
            ['code' => 'TH', 'name' => 'Thailand'],
            ['code' => 'TG', 'name' => 'Togo'],
            ['code' => 'TK', 'name' => 'Tokelau'],
            ['code' => 'TO', 'name' => 'Tonga'],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago'],
            ['code' => 'TN', 'name' => 'Tunisia'],
            ['code' => 'TR', 'name' => 'Turkey'],
            ['code' => 'TM', 'name' => 'Turkmenistan'],
            ['code' => 'TV', 'name' => 'Tuvalu'],
            ['code' => 'UG', 'name' => 'Uganda'],
            ['code' => 'UA', 'name' => 'Ukraine'],
            ['code' => 'GB', 'name' => 'United Kingdom'],
            ['code' => 'UY', 'name' => 'Uruguay'],
            ['code' => 'UZ', 'name' => 'Uzbekistan'],
            ['code' => 'VU', 'name' => 'Vanuatu'],
            ['code' => 'VE', 'name' => 'Venezuela'],
            ['code' => 'VN', 'name' => 'Vietnam'],
            ['code' => 'WF', 'name' => 'Wallis and Futuna'],
            ['code' => 'EH', 'name' => 'Western Sahara'],
            ['code' => 'YE', 'name' => 'Yemen'],
            ['code' => 'ZM', 'name' => 'Zambia'],
            ['code' => 'ZW', 'name' => 'Zimbabwe']
        ];
        

        foreach ($countries as $country) {
            Country::create([
                'name' => $country['name'],
                'code' => $country['code'],
                'is_active' => true,
                'area' => isset( $country['area'] ) ? $country['area'] : null
            ]);
        }
    }
}
